base:
   dataFolder: ["source", "results", "clean", "run"]
   docsFolder: [ "figures"]
   tmpFolder:  ["tmp"]
   init_git: true
   init_renv: true
   code_subfolder: ["src", "src/functions" , "src/configs"]
   global: false
   libs: ""
   create_folders: true
   files: [ "src/pre-processing.R", "src/post-processing.R", "src/processing.R", "src/functions/000_setup.R" ,"src/main-control.R"]
baseSpatial:
   dataFolder: ["level0", "level1", "level2", "run" ,"rawdata"]
   docsFolder: [ "figures"]
   tmpFolder:  ["tmp"]
   code_subfolder: ["src", "src/functions" , "src/configs"]   
   init_git: true
   init_renv: true   
   global: false
   libs: ["terra", "stars", "sf" , "RStoolbox", "tmap" , "mapview", "dplyr", "CAST", "link2GI"]
   create_folders: true
   files: [ "src/pre-processing.R", "src/post-processing.R", "src/processing.R", "src/functions/000_setup.R" ,"src/main-control.R"]
advancedSpatial:
   dataFolder: ["level0", "level1", "level2", "run"]
   docsFolder: [ "figures"]
   tmpFolder:  ["tmp"]
   code_subfolder: ["src", "src/functions" , "src/configs"]
   init_git: true
   init_renv: true   
   global: false
   libs: ["terra", "stars", "sf" , "RStoolbox", "tmap" , "mapview" ,"dplyr", "caret" ,"randomforest", "CAST", "link2GI"]
   create_folders: true
   files: [ "src/pre-processing.R", "src/post-processing.R", "src/processing.R", "src/functions/000_setup.R" ,"src/main-control.R"]
 
          

